language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
    - lerna bootstrap
    - yarn test
    - cd packages/cozy-konnector-libs
    - yarn docs
    - set +e
    - (git diff --exit-code -- docs && echo "Docs are up-to-date") || (echo "Docs are not up-to-date, please run yarn docs inside cozy-konnector-libs directory and repush" && false)
